### PR TITLE
generator: move example solutions

### PR DESCRIPTION
**Pull request by hilary**
On hold, pending changes to [configlet](https://github.com/exercism/configlet)

Step 2 of moving example solutions to .meta/solutions: moving the existing solutions 😄 

part of Generator improvements, exercism/xruby#485

### CODE REVIEW

**Comment by hilary** [comment]
hmmmm.... configlet. Haven't dealt with that yet.

**Comment by Insti** [comment]
Why doesn't that bug cause a test failure?

**Comment by hilary** [comment]
That's temporary logic... It doesn't cause a test failure due to mocking.

**Comment by hilary** [comment]
replace with exercism/xruby#613

**Pull request closed without merging**
