### PR TITLE
Deprecated cops, deprecated file patterns

### PR DESCRIPTION
**Pull request by kotp**
Made corrections for deprecated file patterns and style cops

### CODE REVIEW

**Comment by kotp** [comment]
This is not ready, gem version for Rubocop needs to be specified.

**Comment by kotp** [comment]
@kytrinyx Where should we set the version requirement for Rubocop?

**Comment by kytrinyx** [comment]
Is it not in the .travis.yml file? We could add a gemfile, too.

**Comment by kotp** [comment]
It is indeed in the travis file.  What version should we use?  The current version is 0.36.0 and unfortunately, my local check script does not check travis.yml file.

The real problem becomes:  The local check in bin does not enforce the rubocop running version based on the travis config setting, which is the real cause of this confusion.

**Comment by kytrinyx** [comment]
Yeah, let's add a Gemfile -- then we can use bundle exec locally.

If the most recent version of rubocop works with what we have, then we may as well upgrade, I think.

**Comment by kotp** [comment]
This means that the travis file should use `Gemfile` to keep things up to date.  One place to do the configuration.

Then it will not be 'bundle exec locally' bundle exec no matter where.

I have the following code example for the Gemfile.

However, perhaps the travis config file should be to do the needful, with the bundle exec command instead, and then instead of the gem file getting gem information from Travis, travis configuration does its commands from there.

```ruby
source "https://rubygems.org"
require 'yaml'

# We read the travis.yml file and pull information from there
config = YAML.load(IO.read('./.travis.yml')).to_hash

config['install'].each do |g|
  gem_detail = g.split
  # Example lines from travis, ignoring the yaml array directive "- "
  # gem install rubocop -v 0.36.0 --no-document
  # gem install minitest --no-document
  # These will both be appropriate as the 2nd and 4th elements will work with
  # the gem command as parameters appropriately.
  gem gem_detail[2], gem_detail[4]
end
```

 I like the code better that will be coming in shortly though. :)

**Comment by kytrinyx** [comment]
> This means that the travis file should use Gemfile to keep things up to date. One place to do the configuration.
> 
> Then it will not be 'bundle exec locally' but bundle exec no matter where.

Agreed. Also agreed that travis should just bundle and use that.

This all looks good, thanks!

**Pull request merged**
