### PR TITLE
Moving Ruby documentation from https://github.com/exercism/docs/blob/mas...

### PR DESCRIPTION
**Pull request by vguerra**
...ter/app/pages/languages/getting-started-with-ruby.md to this repo.

Details: https://github.com/exercism/rossconf/issues/1

### CODE REVIEW

**Comment by kytrinyx** [comment]
This is failing CI because the `make` file is trying to run tests for `docs`. If you have a moment would you see if you can figure out how to get `make test` to ignore it? If you do figure it out, it would be great to have this in the README in this repository.

**Comment by vguerra** [comment]
it passes now \o/. Makefile had already an IGNOREDIRS var that specifies a regexp to ignore dirs that have no tests.

**Comment by kytrinyx** [comment]
Sweet :) Would you mind squashing the commits? Also, the commit history would probably be easier to understand if the commit message doesn't have the file name in the first line. Maybe something like: _Add track-specific documentation_

**Comment by vguerra** [comment]
ok great.. I did squash the commits and travis build passes.

**Comment by kytrinyx** [comment]
Thank you :heart:

**Pull request merged**
