### PR TITLE
Updated bracket-push tests

### PR DESCRIPTION
**Pull request by ebiven**
The tests for bracket-push miss a class of problems where an unopened
backet is closed for solutions which only track opened brackets.

### CODE REVIEW

**Comment by Insti** [comment]
Thanks a lot @ebiven 

Is this case covered by the common test data? See: https://github.com/exercism/x-common/blob/master/bracket-push.json  
If not it would be helpful to add it there as well.

**Comment by ebiven** [comment]
@Insti Looks like it isn't covered there either. I'll make a PR for that as well. Oddly enough the Elixir test cases for this problem do cover it.

**Comment by Insti** [comment]
The test cases for this problem are generated from the common .json file, so once https://github.com/exercism/x-common/pull/301 has been merged we can re-generate the tests for this problem, which will pull in the new case and update the version number.

**Comment by Insti** [comment]
@ebiven the x-common changes have now been merged, did you want to work out how to re-generate the tests and add that to this PR? 
There are some instructions here: https://github.com/exercism/xruby#generated-test-suites
Assuming your x-common repository is up to date you should just need to run:
`xruby/bin/generate-bracket-push`

**Comment by ebiven** [comment]
@Insti : Should be ready now.

**Comment by Insti** [comment]
Looks good.

**Comment by Insti** [comment]
Thanks a lot @ebiven, great work!
I really appreciate your help and willingness to keep completing all the extra little tasks that appeared after what was an apparently simple initial pull request. :heart:

**Comment by ebiven** [comment]
No problem. I got a months worth of entertainment out of it.

**Pull request merged**
