### PR TITLE
Clean up 'food-chain'

### PR DESCRIPTION
**Pull request by kytrinyx**
- Normalize "expected" strings.
- Replace instance methods with class methods.
- Implement example as a module rather than a class.
- Rename module to FoodChain instead of FoodChainSong.
- Rename `sing` to `song` (noun for consistency with other methods).
- Remove trailing newline on last line of each verse (if I were to write the song down in a file, I wouldn't have a blank line at the very end of the song).
- Add a VERSION constant for book-keeping purposes.
- Replace logic with value in test for 'song'

### CODE REVIEW

**Comment by kytrinyx** [comment]
@kotp I overhauled the entire problem. If you have any thoughts on this, I'd love to discuss the choices.

**Comment by kotp** [comment]
Peeking.

**Comment by kotp** [comment]
The above pull request is only a pull request against this branch, not master.

**Comment by kytrinyx** [comment]
Thanks for helping think this through, @kotp. I think the result is a huge improvement to what we had earlier.

**Comment by NobbZ** [comment]
The biggest problem with this approach I see, there are so many solutions out there, that just open the file and return its content. No one cares for `#verse` and `#verses` anymore, they all just do `#song`.

**Comment by kytrinyx** [comment]
Interesting. So we should probably add tests back in for those, to enforce some sort of algorithmic approach.

**Comment by kotp** [comment]
Verses is still being tested though, I will have to look at recent submissions for this exercism to note what @NobbZ is stating.  @NobbZ any idea on how to test to enforce a more dynamic solution?

**Pull request merged**
