### PR TITLE
(The sum of) Two sides can be equal but not less than third.

### PR DESCRIPTION
**Pull request by kotp**
re: #247

### CODE REVIEW

**Comment by kytrinyx** [comment]
I think that we should also have a test for the edge case where two sides exactly equal the third. Thoughts?

**Comment by kotp** [comment]
Yes, I think the original triangle that was created is a good test for this.

**Comment by kytrinyx** [comment]
There's more discussion in some of the other tracks about degenerate triangles: https://github.com/exercism/xerlang/issues/85

**Comment by kotp** [comment]
Looking at the erlang.  Left message there.  I don't think this exercise is suited for getting into post elementary geometry, it isn't the point of the exercise.  We don't cover more than three well known and standard triangles, out of the six that we learn about in 3rd or 4th grade.  Before we make statements about degeneracy, we have room to expand on the other three types of triangles that have area.

**Comment by kotp** [comment]
Leave it as is, not taking into account degenerative values, see conversation: exercism/xerlang#85

**Pull request closed without merging**
