### PR TITLE
Queen-Attack missing test cases #439

### PR DESCRIPTION
**Pull request by remcopeereboom**
Removed test for default positions. It seems arbitrary for the given
problem, the common tests don't include it as a requirement and it seems
best to leave this as a design decision.

Added tests to ensure that queens are placed on the board.

Refactored test to use an inline block, same as the other tests.

Added a version constant test.

### CODE REVIEW

**Comment by kotp** [comment]
Should this also be coordinated with a change for [queen-attack/canonical-data.json](https://github.com/exercism/x-common/blob/master/exercises/queen-attack/canonical-data.json) as a pull request?  I you opened up exercism/x-common#396 and if you are working on the generator, I would say proceed with that, and work on this proposal via a PR in the `.json` file.

That way, it isn't a fixed locally, then generated with the current, and then fixed with the data.

**Comment by remcopeereboom** [comment]
> Of course, if you aren't knee deep in the generator, then fixing it and having it sooner is better than later.

I was working on the generator code, but I had some deeper issues with it that I can't quite recall right now. I think I was unhappy with the common json test data as it was currently and I didn't want to change it because I'm not sure how other languages use it. And I don't want to implement a generator for the current json data if it's going to be changed. Either way, I felt it best to patch up the tests in the meantime.

Note that it says travis failing, but I'm not getting any details as to why. Any ideas?

**Comment by remcopeereboom** [comment]
Is the build failing for a test implementation of queen attack? I couldn't find one in the repository. Did I miss it?

**Comment by remcopeereboom** [comment]
Okay, see it now: `example.rb`. I was looking for `queen_attack.rb`. Will update and resubmit.

Closing this, we can move the discussion to #439 or to the new submission.

**Pull request closed without merging**
