### PR TITLE
Rewrite gigasecond problem generator

### PR DESCRIPTION
**Pull request by kytrinyx**
This uses the new style of generator based on lib/generator.

Incidentally, it also fixes the last rubocop style violation.

### CODE REVIEW

**Comment by kotp** [comment]
Was failing CI, added VERSION in `example.rb`.

**Comment by kytrinyx** [comment]
Gah, I thought I tested, but I must have tested _before_ adding the book-keeping test. Thanks for fixing it.

**Comment by kotp** [comment]
No worries, it was definitely tested afterward as well.  CI for the win...

**Comment by kytrinyx** [comment]
OK, shipping this. I think this means we can add rubocop to the travis build.

**Pull request merged**
