### PR TITLE
Update config.json to match new specification

### PR DESCRIPTION
**Pull request by Roshanjossey**
This addresses issue #419

https://github.com/exercism/xruby/issues/419

### CODE REVIEW

**Comment by Insti** [comment]
Thanks @Roshanjossey 
I'm not sure why this has not been merged yet, maybe it just got overlooked.
@ktop?

**Comment by Insti** [comment]
Thanks a lot @Roshanjossey, :heart: sorry it took us so long to merge this.

**Comment by Roshanjossey** [comment]
Awesome @Insti.
How are we going about the next steps in updating config.json? Like adding topics and difficulty.
Does it make sense to take reference similar language streams? I believe some language steams have already done this.
https://github.com/exercism/xswift/pull/186

**Comment by Insti** [comment]
Good questions @Roshanjossey , could you create an issue here in xruby so we can discuss them. Do you have any suggestions about how we should proceed?

**Comment by Roshanjossey** [comment]
@Insti: Sorry for taking so much time to reply to this.
I'll be creating an issue for the same.
I thought it'd be better to keep track of everything related to that change in this issue itself

**Pull request merged**
