### PR TITLE
Ensures designers ruby at version 2.1.2 or higher

### PR DESCRIPTION
**Pull request by kotp**
#371 discussion about helping ensure we are reporting on older versions of Ruby for exercise developers.

### CODE REVIEW

**Comment by Cohen-Carlisle** [comment]
I think the string is being interpreted literally, as in, ruby is now looking for a ruby version called `>= 2.1.2` instead of a ruby version that is greater than or equal to `2.1.2`

Is there a reason for `2.1.2` over say, `2.1.0`?

**Comment by kotp** [comment]
Seems like Travis CI is set to 2.1.x these two should match, so I am lowering the minimum Ruby version to match that rather than what is required for repository `exercism-io`.

Strange, the specification is failing in Travis CI, though Bundle version specification in Gemfile is correctly formatted.  A Travis bug?  Checking for that possibility.

**Comment by kotp** [comment]
The version string is technically correct for Gemfile, it seems Travis is comparing it in a manner than doesn't account for that in the Gemfile.  I think I asked Travis team the same thing, it appears to check it 'stringally' rather than 'versionally'.

**Comment by kotp** [comment]
And I would say "Yes, there is some reason."  But I do not know what the reason is.  Could be an end of life point, would likely have to check the commit history for that file, if it was annotated for the change, or it was a 'convenience' change at that point.

**Comment by kotp** [comment]
Closing due to lack of interest, and it is possible to do this locally, away from the repository.

**Comment by kytrinyx** [comment]
Thanks, @kotp, I think that was the right choice.

**Pull request closed without merging**
