### PR TITLE
Robot-name: Add in BookKeeping comment

### PR DESCRIPTION
**Pull request by pachonk**
Simple addition of BookKeeping comment

### CODE REVIEW

**Comment by kotp** [comment]
This exercise is not generated, and so is still at version 0.  @pachonk, would you be interested in writing the generator for this exercise?

**Comment by pachonk** [comment]
@kotp I don't mind, but what is "generated" exercise?

**Comment by pachonk** [comment]
Ah, the *.tt and .meta stuff?

**Comment by kotp** [comment]
Yes, and it is related to the `bin/generate` command and the `lib/*_generator.rb` file that will be required.

@Insti which is the current "exemplar" generator exercise at the moment to use as a reference?  Suitable for this?  Maybe Hamming...

**Comment by kotp** [comment]
@pachonk If you have time this weekend, I should have time as well.

**Comment by pachonk** [comment]
@kotp Is Hamming the prime example?

**Comment by kotp** [comment]
I think leap or pangram or leap may be better examples... there is something in Hamming that is not the same as the others.

**Comment by kotp** [comment]
Now that canonical data is using a schema I think this is prime to be done, @pachonk.

**Comment by pachonk** [comment]
Closing, will make new PR when I'm finished.

**Pull request closed without merging**
