### PR TITLE
Add the "first patch" labels to exempt from stale

### PR DESCRIPTION
**Pull request by kotp**
@tejasbuane had the idea of keeping the these accepted work units to be
kept from becoming stale.

### CODE REVIEW

**Comment by Insti** [comment]
Is this a good idea? 
If they are marked stale by probot we should review them to see if they are still relevant.

**Comment by kotp** [comment]
That is why it is here.  Unsure if it is a good idea.  But all first_time style issues should be reviewed periodically anyway, as complications from other developments could move it from an 'easier' change to something that is no longer appropriate for first time pull requests.

**Comment by Insti** [comment]
Ok, well I vote no.
Let's have probot remind us about the things we might not have looked at for a while.

**Comment by kotp** [comment]
That works... And Probot should definitely help with that.

**Pull request closed without merging**
