### PR TITLE
Add test generator for "binary" exercise

### PR DESCRIPTION
**Pull request by tommyschaefer**
I recently came across #381, and saw that @kytrinyx suggesting converting all existing exercises to use generated tests as a first step.

I was wondering if this is still a goal? If so, I would love to help work on that! 😄

To start this off, I've added a generator for the "binary" example.

Thank you so much for your time, and I look forward to your feedback!

### CODE REVIEW

**Comment by tommyschaefer** [comment]
Also, here's the test data for the binary example:

```json
{
   "cases": [
      {
         "description": "binary 0 is decimal 0",
         "number": "0",
         "expected": 0
      },
      {
         "description": "binary 1 is decimal 1",
         "number": "1",
         "expected": 1
      },
      {
         "description": "binary 10 is decimal 2",
         "number": "10",
         "expected": 2
      },
      {
         "description": "binary 11 is decimal 3",
         "number": "11",
         "expected": 3
      },
      {
         "description": "binary 100 is decimal 4",
         "number": "100",
         "expected": 4
      },
      {
         "description": "binary 1001 is decimal 9",
         "number": "1001",
         "expected": 9
      },
      {
         "description": "binary 11010 is decimal 26",
         "number": "11010",
         "expected": 26
      },
      {
         "description": "binary 10001101000 is decimal 1128",
         "number": "10001101000",
         "expected": 1128
      },
      {
         "description": "binary ignores leading zeros",
         "number": "000011111",
         "expected": 31
      },
      {
         "description": "invalid binary numbers raise an error",
         "number": ["012", "10nope", "nope10", "10nope10", "001 nope", "2"],
         "expected": -1
      }
   ]
}
```

**Comment by Insti** [comment]
Nice work @tommyschaefer, Yes this is something that still needs to be done.

> Is this best for one pull request? Or should each addition be it's own PR? 

I think each problem should be in it's own PR. There are often issues discovered during this process that require further discussion and these are best handled on a case-by-case basis and without needing to block other simpler ones. 

> Also, in some cases test data needs to be added to the exercism/x-common, so should I also open PR's on that repo?

Yes additions/modifications to the <problem-name>.json files will need to be added as PRs on the x-common repository.

**Comment by tommyschaefer** [comment]
Okay great! Thank you so much for the feedback!

I've updated the description and title of this pull request to only refer to the `binary` exercise. Also, I opened a PR at exercism/x-common#296 to add the JSON test data above!

**Comment by Insti** [comment]
@tommyschaefer will you create an issue here in the xruby repository with your list of problems that require generators so we can track progress towards implementing them all?

**Comment by Insti** [comment]
You should probably also be mindful of #386 - "Audit test files for assert/refute with no custom message"
I think the general intention is that assertion failures have helpful error messages.

**Comment by tommyschaefer** [comment]
> Will you create an issue here in the xruby repository with your list of problems that require generators so we can track progress towards implementing them all?

Absolutely! This is now at: #396

> You should probably also be mindful of #386 - "Audit test files for assert/refute with no custom message"
I think the general intention is that assertion failures have helpful error messages.

Ah! Excellent! Thank you for pointing that out 😄 I didn't see that initially, so I will keep that in mind and make some adjustments!

**Comment by Insti** [comment]
Before you spend too much time working on the generator for `binary` you probably should know that it is [being depricated](https://github.com/exercism/x-common/issues/279). So it might be better to work on one of the other problems.

**Comment by kotp** [comment]
Good catch on that @insti though it is a good practice one.  It is simple, and doesn't have nested cases.

**Comment by tommyschaefer** [comment]
Ah yes! I didn't see that before. Thank's for the heads up @Insti 😄

**Comment by Insti** [comment]
Merge this? :+1: :-1: 

Argument for: The work has been done, it looks good, the problem is not deprecated yet.
Minor issue: Not sure the test file changes warrant a version bump from 2 to 3.

**Comment by kotp** [comment]
Version bump can happen, we will make more room for it.

**Comment by kytrinyx** [comment]
If solutions that pass the ungenerated test file would also pass the generated one, I wouldn't change the version.

**Comment by Insti** [comment]
@tommyschaefer are you able to change the test version back from 3 to 2?
Then we can merge this.

**Comment by tommyschaefer** [comment]
@Insti Absolutely! I've changed the test version back to 2 😄

**Comment by Insti** [comment]
Thanks for your work on this @tommyschaefer 
I've merged in these changes, we'll need to remember to re-run the generator once https://github.com/exercism/x-common/pull/296 is complete.

**Comment by Insti** [comment]
I think I made a mistake by merging this before the [x-common data](https://github.com/exercism/x-common/pull/296) was complete.
I've decided to "fail forwards" by merging that in as well rather than trying to back this change out and creating more confusion than necessary.

**Pull request merged**
