### PR TITLE
Make acronym table-driven

### PR DESCRIPTION
**Pull request by kytrinyx**
This may or may not be a good idea. It's not very idiomatic Ruby, but
in this case I think that it's very easy to read, and serves well as documentation.

### CODE REVIEW

**Comment by kotp** [comment]
I do this in my [LearnRubyByTesting](https://bitbucket.org/kotp/learnrubybytesting/src/b8fdf81a9289e4986f544ccbcfc2b5ad6a81d5ea/test/core_ruby_string_spec.rb?at=master) repository.  The way that it is done still documents individual tests (When I use Spec reporter) and has messages for failures as appropriate. so the data used to test (and message) is all in one place and it looks like a table.

I like it.  I have linked to the full test above so you can peek.  Around lines (153..-1)

```ruby
 describe 'Formatting' do

    Formatting_code_and_result.each do |format_code, value, result, comment|
      it "must format '%#{format_code}' % #{comment || value} to '#{result}'" do
        ("%#{format_code}" % value).must_equal result
      end
    end

  end

end

BEGIN {
  Formatting_code_and_result = [
    ##  fields are:
    #format_code, value,   expected_result, failure comment
    ['b',    42,              '101010'              ],
    ['B',    42,              '101010'              ],
    ['s',    'string',        'string'              ],
    ['d',    42,              '42'                  ],
    ['i',    42,              '42'                  ], # Identical to d format code above
    ['u',    42,              '42'                  ], # Identical to d format code above
    ['05d',  42,              '00042'               ],
    ['5d',   42,              '   42'               ],
    ['o',    42,              '52'                  ], # convert to octal
    ['x',    42,              '2a'                  ],
    ['X',    42,              '2A'                  ],
    ['e',    42,              '4.200000e+01'        ],
    ['9.2e', 42,              ' 4.20e+01'           ],
    ['E',    42,              '4.200000E+01'        ],
    ['9.2E', 42,              ' 4.20E+01'           ],
    ['g',    42,              '42'                  ],
    ['g',    42123,           '42123'               ],
    ['9.2g', 42,              '       42'           ],
    ['9.2g', 42**-2,          '  0.00057', '42**-2' ],
    ['9.2g', 42**-3,          '  1.3e-05', '42**-3' ],
    ['9.2g', 42** 2,          '  1.8e+03', '42** 2' ],
    ['9.2G', 42** 4,          '  3.1E+06', '42** 4' ], # Hard to spot, but this capitalizes the E
    ['f',    42,              '42.000000'           ],
    ['.2f',  42,              '42.00'               ],
    ['.5a',  1,               '0x1.00000p+0'        ], # Figured this out.  Checkout 1024, it shows p as a binary to power of 10
    ['.5a',  1024,            '0x1.00000p+10'       ],
  ]
}
```

**Comment by kytrinyx** [comment]
I like how you document the failure in your table test. I've updated the test to have an additional failure message that includes the input.

**Comment by kotp** [comment]
:shipit:  Works well, and looks good.

**Comment by kotp** [comment]
See commit 536b89f as I moved the table out of the test.  Style complaint averted.

**Comment by kytrinyx** [comment]
Nice catch! Thanks :)

**Pull request merged**
