### PR TITLE
Removes the getting started and 'file not found' code from the hamming exercise

### PR DESCRIPTION
**Pull request by trayo**
This PR is for when the hamming exercise is ready to become the second exercise.

#130

### CODE REVIEW

**Comment by kotp** [comment]
:+1:

**Comment by kytrinyx** [comment]
Sweet!

Go ahead and rebase onto the most recent master, and then check out this section of the README to see if it makes sense:

https://github.com/exercism/xruby#generated-problems

**Comment by trayo** [comment]
I went ahead and pushed the rebase. The example makes more sense now. Do I need to update this PR by editing the example generators instead?

**Comment by kytrinyx** [comment]
If you edit the `example.tt` file in addition to what you have here, then we're all good.

**Comment by trayo** [comment]
I updated the example.tt and removed the same code that was removed from hamming_test.rb

**Comment by kotp** [comment]
:shipit: Looking good!  Thanks, @trayo for all the hard work!

**Comment by kytrinyx** [comment]
Thanks so much @trayo!

**Pull request merged**
