### PR TITLE
Rubocop: Enable space after comma cop

### PR DESCRIPTION
**Pull request by Insti**
@kotp flagged a missing space after comma in a review: https://github.com/exercism/xruby/pull/540#pullrequestreview-16715930

This patch enables the Style/SpaceAfterComma cop so that this can be automatically detected and fixed by Rubocop.

### CODE REVIEW

**Comment by kotp** [comment]
Will the rubocop change impact current code?

**Comment by Insti** [comment]
> Will the rubocop change impact current code?

There are 15 files that fail this check, they are fixed in the second commit of this PR: https://github.com/exercism/xruby/pull/542/commits/bed3b50dcf082dc5c9dc032517a429442f056e18

**Comment by kotp** [comment]
Should the rubocop config file exclude the example.rb files?  You know I like to tread lightly on the example files, as they are "Proof of Solvability", and not necessarily optimal or idiomatic.

**Comment by Insti** [comment]
> Should the rubocop config file exclude the example.rb files?

No.

It's good for the entire repository to have a consistent style.
This cop is auto-correctable, so ensuring it is correct is just a matter of running `rubocop -a`

**Pull request merged**
