### PR TITLE
Fast alphametics solver (uses simplified partial equations to limit…

### PR DESCRIPTION
**Pull request by moveson**
…set of viable permutations) 
@Insti Please review and merge with PR #469.

### CODE REVIEW

**Comment by Insti** [comment]
Awesome, thanks @moveson :heart:

**Comment by Insti** [comment]
Why does it think there are conflicts?
(Not that it really matters, but I'm guessing if you rebased this branch off master it would fix it.)

**Comment by kotp** [comment]
Why was this closed?

**Comment by moveson** [comment]
My branch was behind and that was creating conflicts. I deleted the branch, created a new one, and opened a new PR #477.

**Comment by kotp** [comment]
Hopefully next time you have it figured out so that won't need to happen. You can always bring your branch up to date. :)  I am happy to work through git issues like this with you, well worth knowing how to do that.

**Pull request closed without merging**
