### PR TITLE
add bracket-push

### PR DESCRIPTION
**Pull request by moofkit**
Starting bracket push exercise

### CODE REVIEW

**Comment by moofkit** [comment]
ready for review

**Comment by kytrinyx** [comment]
I like the use of `refute` and `assert` in the test suite. This looks good to me. I'd love a second opinion, @kotp & @Cohen-Carlisle!

**Comment by Cohen-Carlisle** [comment]
I like it, thanks, @moofkit!
This is a great starting point and I think it could be merged as is.

There is ambiguity around when we use `VERSION`. Do we reserve it only for generated exercises? I think it makes sense to always use it (as is done here).

The biggest thing I'd like to see added is input string with non-bracket chars (e.g., letters, numbers, etc.), but that could always be another PR.
Longer term, I'd also love to get test data in a JSON file in [x-common](https://github.com/exercism/x-common).

**Comment by kotp** [comment]
[Versions](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#exercise-versioning) for information on what we have been doing for versions.  If there needs to be some clarification, that would be the place to update.

**Comment by moofkit** [comment]
Thank's to all for review! That's my first OS PR 🎉 

I can implement testing data for this exercise in [x-common](https://github.com/exercism/x-common)

**Comment by kotp** [comment]
Looks good.  Note about the raising of exception classes with helpful messages, but good to go.

**Comment by kotp** [comment]
Merge complete 44d46de9

**Comment by kytrinyx** [comment]
Quick note on versions: I'd like to have them everywhere, since we sometimes make changes to non-generated test suites, causing them to be backwards-incompatible.

Congrats on your first OS PR, @moofkit!

**Comment by kytrinyx** [comment]
BTW: I mentioned this conversation in today's "Behind the Scenes" newsletter. http://tinyletter.com/exercism/letters/exercism-it-s-about-the-conversations

**Pull request closed without merging**
