### PR TITLE
Refactor hamming test generator

### PR DESCRIPTION
**Pull request by kytrinyx**
This uses an erb template (example.tt), and moves supporting code into a
new lib directory.

The actual generator lives in bin/generate-hamming

I also added a book-keeping test (`VERSION`) and a comment that lets us know which SHA the shared metadata was at when the problem was last generated.

### CODE REVIEW

**Comment by kotp** [comment]
Code looks good.

It should be made clear that the point at which the version needs to be incremented.  We have 3 occurrences of this happening.  The `.version` file, the test and the solution file the user is writing.  Are there any that need to be manually done?  (The user solution file?)

Otherwise, it looks pretty solid from what I can see at the moment.

**Comment by kytrinyx** [comment]
The .version doesn't need to be incremented manually, though if you regenerate the solution multiple times you'll want to git checkout the .version file. I'll add something more to the README around this.

The example solution does have to be incremented manually at the moment, but we could easily solve that with the generator script. I'll fix that.

**Comment by kytrinyx** [comment]
I've updated the generator to also update the example.rb file.

**Comment by kotp** [comment]
What about the coders file? (This is doable due to the required name being in the test itself in the require line?)  Or is this strictly  user responsibility?

**Comment by kytrinyx** [comment]
The coder's file is the user's responsibility, in my opinion.

**Comment by kotp** [comment]
This looks good to me, added some style changes. Gets a :shipit: vote from me.

**Comment by kytrinyx** [comment]
Yeah, those style changes make sense. There's one thing that needs to be changed in the text template, I'll fix it tonight if you don't get to it before I do.

**Comment by kotp** [comment]
Waiting on a :shipit:  from you or another member.  Things should now be persistent.

**Comment by kytrinyx** [comment]
w00t

**Pull request merged**
