### PR TITLE
Grade school patch

### PR DESCRIPTION
**Pull request by remcopeereboom**
Changed grade-school problem to use `#to_h` instead of `#to_hash`.

### CODE REVIEW

**Comment by kytrinyx** [comment]
@remcopeereboom Do you have a very old version of the ruby repository? We had a bit of a snafu where we had to edit the history: https://github.com/exercism/xruby/issues/28

Would you mind resetting --hard with master and then cherry-picking your patch into a fresh branch?

**Comment by remcopeereboom** [comment]
@kytrinyx - Strange, I just forked the same day. It should be okay now.

**Comment by remcopeereboom** [comment]
@kytrinyx Strange. I forked only minutes before. I have rebased and all should be well now.

**Comment by kytrinyx** [comment]
Very strange! This looks great now. Thanks!

**Pull request merged**
