### PR TITLE
binary: Add error handling

### PR DESCRIPTION
**Pull request by kytrinyx**
This adds some additional test cases to clarify the behavior around
the conversion of valid/invalid binary input.

See https://github.com/exercism/x-common/issues/95

### CODE REVIEW

**Comment by kotp** [comment]
The example does not adhere to the "do the conversion yourself" but it is a sanity check that everything is working as it should be... trusting the implementers of the language more than a 'self made' solution.  The educational value is not in the example.rb file itself, so I think this is OK to do.

**Comment by kytrinyx** [comment]
> The example does not adhere to the "do the conversion yourself" but it is a sanity check that everything is working as it should be... trusting the implementers of the language more than a 'self made' solution.

I'm not sure what you mean. The example does the conversion manually.

**Comment by kotp** [comment]
Yes, but it uses a built in method that does this conveniently, rather than writing the implementation explicitly.  Using to_s(base) is probably not really the goal, based on the README.  But it is definitely good as the definitive example that is expected in the way that it is to work.

**Comment by kotp** [comment]
Specifically, my changes to `example.rb` as:

```
  def to_decimal
    digits.to_i(2)
  end
```

**Comment by kytrinyx** [comment]
The point is to _not_ use `to_s(base)`, though.

**Comment by kytrinyx** [comment]
Oh, I didn't see your changes. That makes sense. I don't want to use digits.to_i(2) since the whole point of the exercise is to understand binary conversion enough to do it manually.

**Comment by kotp** [comment]
Yes, but the nitpickers don't see the example, right?  It is a different view point?

**Comment by kotp** [comment]
if I do the 'thing to measure against' in the tests, then it sort of exposes this.  If I leave it in the more 'hidden' example.rb file, then it does what is intended, cleanly.

**Comment by kytrinyx** [comment]
Right now the example solution is only used to test the test suite. I guess that means that it's OK to use a solution that would be discouraged on the site, but it seems wrong to me in a way that I'm unable to articulate.

**Comment by kotp** [comment]
I have the same little nag as well.  I think it is because of the conflicting point of view.  It does potentially avoid bugs that a 'homegrown' solution could introduce though.

**Comment by kytrinyx** [comment]
I see how it could avoid the bugs that a homegrown solution might have, but this is really a trivial problem, and the homegrown solution shouldn't have bugs.

**Comment by kotp** [comment]
Then just the style changes then...

**Comment by kytrinyx** [comment]
Okay :)

**Pull request merged**
