### PR TITLE
Update ruby generator

### PR DESCRIPTION
**Pull request by bmulvihill**
Use new x-common directory structure

### CODE REVIEW

**Comment by Insti** [comment]
Travis is failing due to Rubocop being quite strict.
```
C: 17: 81: Metrics/LineLength: Line is too long. [99/80]
```

There are a few of options: 
1 Refactor so it's not a problem.
2 Add a `\#rubocop:disable Metric/LineLength` comment around that line.
3 Ignore it for now because it's not super important and we're soon going to be making Rubocop less pedantic.

So choose which one you prefer.

**Comment by bmulvihill** [comment]
Yeah I saw that Ill fix it

**Comment by bmulvihill** [comment]
Ok I disabled the warning for now

**Comment by Insti** [comment]
Great! Thanks @bmulvihill :heart:

**Pull request merged**
