### PR TITLE
Move exercise foldres to subdirectory (xruby)

### PR DESCRIPTION
**Pull request by kotp**
references #240

### CODE REVIEW

**Comment by kytrinyx** [comment]
It looks like `make test` is failing.

**Comment by kotp** [comment]
Does the test account for the exercises folder but not having an exercises.rb file in that folder?

> cannot stat ‘exercises/example.rb’

**Comment by kytrinyx** [comment]
Good question. Does the test use the config.yaml which hasn't put "exercises" in the ignore section?

**Comment by kotp** [comment]
Found it, in the travis config.

**Comment by kotp** [comment]
The check for ending whitespace disabled early on in the tests, due to the current requirement to have padding in the heredocs construction.  Doesn't exactly go with the 'fix' but it slipped through earlier commits, when it should have been failing CI all along.

**Comment by kytrinyx** [comment]
Right, that makes sense. Thanks!

**Pull request merged**
