### PR TITLE
Removed of_rna transcription logic and tests for rna_transcription exercise

### LINKED ISSUE #231: Transcription doesn't go both ways... only DNA to RNA
This is part of a larger [issue] (https://github.com/exercism/x-common/issues/148) to remove RNA to DNA "transcription" from the `rna-transcription` exercise across all languages.

Files to edit are [here](https://github.com/exercism/xruby/tree/master/rna-transcription).

### PR DESCRIPTION
**Pull request by mhelmetag**
Fixes #231

Tested locally:
```
ruby rna-transcription/rna_transcription_test.rb 
Run options: --seed 27636

# Running:

.........

Finished in 0.001411s, 6378.4550 runs/s, 6378.4550 assertions/s.

9 runs, 9 assertions, 0 failures, 0 errors, 0 skips
```

Also cleaned up `example.tt` to look more like the others. Everything was nested in some phantom block string...

### CODE REVIEW

**Comment by kytrinyx** [comment]
This is missing all of the skips in the test suite, I think.

**Comment by mhelmetag** [comment]
Oh snap... Good catch. Will update.

**Comment by mhelmetag** [comment]
Updated

**Comment by kytrinyx** [comment]
Would you mind squashing the commits?

http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request

**Comment by mhelmetag** [comment]
Never squashed before. Pretty cool.

**Comment by kytrinyx** [comment]
:tada:

**Pull request merged**
