### PR TITLE
93 make tests executable

### PR DESCRIPTION
**Pull request by kotp**
Actually changes the mode of the test files to executable bit, adds some tools to bin, and includes a test for each test file to check if it is in fact executable.

re #93 and #155

### CODE REVIEW

**Comment by kytrinyx** [comment]
Yeah, I think that a tool for this is a good approach, especially seeing as we have other tools already.

Maybe we can add a make task that runs all the various tools to make it easy/quick to check everything before committing.

**Comment by kotp** [comment]
A git commit hook?

**Comment by kotp** [comment]
Thanks @kytrinyx I was hoping you liked it.

**Comment by kytrinyx** [comment]
I would definitely make it a git commit hook. I always forget, otherwise.

**Comment by kotp** [comment]
See #159

**Pull request merged**
