### PR TITLE
Add diamond

### PR DESCRIPTION
**Pull request by cloudleo**
Working on Diamond

### CODE REVIEW

**Comment by Insti** [comment]
Thanks for deciding to help us add exercises to Exercism.
It's been a while since you marked this as a Work-In-Progress, are you still working on this?
If you are, is there anything you need help with?
If you're not, use the 'close request' button on Github so someone else can work on adding the problem.

If we don't hear back from you, we will close it ourselves one week from now. 
(On or after the 30th July 2016)

**Comment by cloudleo** [comment]
@Insti Hi
I have actually finished a long time ago, I just been very occupied lately.  I apologize, I will push the solution up by tomorrow.

**Comment by Insti** [comment]
Awesome! Thanks for letting us know @cloudleo

**Comment by cloudleo** [comment]
@Insti Hi, Thanks for being patient but I believe I am having a hard time indenting , its looks right to me locally but until I push it up ...its everywhere

**Comment by Insti** [comment]
@cloudleo your text editor probably has a setting to "convert/expand tabs to spaces" make sure that is on, and your tab width is set to 2.

**Comment by cloudleo** [comment]
@insti YES!!! i squashed my recent commits into one and got correct indentions ...thanks!!! Would you let me know what other changes I might need to do or any feedback?

**Comment by Insti** [comment]
Also, you'll need to do some messing around with git to get your changes submitted here properly.

* Checkout the `diamond` branch `git checkout diamond`
* Merge in the changes you've made `git merge master`
* push the diamond branch to your cloudleo/xruby repository. `git push`

If all that goes well, then they should show up here automatically.

**Comment by Insti** [comment]
You can also come to the chat at https://gitter.im/exercism/dev if you have 'real time' questions.

**Comment by cloudleo** [comment]
@Insti  Morning! so I tried to squash all my commits into one and it seems i over squashed that I squashed other people commits, I am sure that is a bad thing, should I or is there a way to reverse it?

**Comment by Insti** [comment]
@cloudleo sometimes it can be best to start again. :)

`git branch -m diamond diamond_mess`
`git checkout master`
`git checkout -b diamond`

`git checkout diamond_mess <files you want>`
commit them
try pushing the branch again.

**Comment by cloudleo** [comment]
@Insti I think it worked but its not passing the Travis CI

**Comment by Insti** [comment]
You're making progress at least!

Travis CI is failing because of the rubocop checks.
Run: `bundle exec rubocop -a -D example.rb diamond_test.rb`
That will automatically fix the ones it can.

**Comment by Insti** [comment]
There will be some it cannot fix, 3 about snake_case method names, just rename the methods using lowercase letters.
1 about a test that is too long, for that put: 
```
# rubocop:disable Metrics/MethodLength
```
at the top of the file.

**Comment by cloudleo** [comment]
@Insti did it passed? it told me it failed again due to

exercises/diamond/diamond_test.rb#test_0001_should have the execution bit set [bin/executable-tests-check:7]:
Execution bit not set for exercises/diamond/diamond_test.rb

**Comment by Insti** [comment]
`chmod +x exercises/diamond/diamond_test.rb` will fix it. (Without me needing to give a long tutorial on file system permission bits.)

**Comment by Insti** [comment]
We're getting really close to being done..

**Comment by cloudleo** [comment]
@Insti It Passed!!!! thanks!!! and I would look that up , wow this was a great journey, my git skills have been leveled up thanks to you

**Comment by Insti** [comment]
Thanks @cloudleo :heart: It's great you kept at it.

**Comment by kotp** [comment]
@cloudleo Thank you for the contribution!

**Pull request merged**
