### PR TITLE
Add version test for Accumulate with updated comment for clarity

### PR DESCRIPTION
**Pull request by kickinbahk**
See [ticket](https://github.com/exercism/xruby/issues/188) for where this was recommended.

### CODE REVIEW

**Comment by kytrinyx** [comment]
It's passing in the very last commit, but I'd really like to do all of these things separately.

Would you mind making a change to just the rna-transcription exercise, and only about updating the `VERSION` documentation?

That way if there's a complaint from travis about that, we can focus in on exactly why.

**Comment by kickinbahk** [comment]
Okay sure! I am still a little new to this open source stuff...would the way that I should do it be to open a branch for each exercise to update the comments?

**Comment by kytrinyx** [comment]
Yepp, a branch for each would be a great idea.

Sometimes (if the change is trivial) it's fine to make the exact same change to all the different exercises at once, but it's easier to review things and easier to merge when the PRs are very distinct.

**Comment by kytrinyx** [comment]
Oh, and I'm always happy to help sort out the details, don't hesitate to ask!

**Pull request closed without merging**
