### PR TITLE
Update RESOURCES.md and add LEARNING.md

### PR DESCRIPTION
**Pull request by rickr**
Hi all, 

I'm proposing a rename of `RESOURCES.md` to `LEARNING.md` as all the links contained in the old `RESOURCES.md` pertain to learning.

### CODE REVIEW

**Comment by Insti** [comment]
Gee, thanks Rick.

Can you also add an empty RESOURCES.md file so that anyone wanting to add actual resources will know where to put them.

Check sure that xruby still conforms to https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md#track-anatomy

**Comment by rickr** [comment]
I'll do one better! Added RESOURCES.md back with some basic resources.

**Comment by Insti** [comment]
Awesome! That's much appreciated.

**Comment by Insti** [comment]
Merged. Welcome to Exercism!
It might take a day or two for the changes to make their way to the live site, but they'll appear there sooner or later.
Thanks a lot for your help.

**Comment by kytrinyx** [comment]
> I'll do one better! Added RESOURCES.md back with some basic resources.

:heart: :heart:

... and it's deployed.

Thanks so much.

**Pull request merged**
