### PR TITLE
Hamming generate tests

### PR DESCRIPTION
**Pull request by r11runner**
hamming exercise:
 - added an example generator
 - regenerated the tests with it

### CODE REVIEW

**Comment by kytrinyx** [comment]
`make test` is failing with the following error:

```
  1) Failure:
HammingTest#test_disallow_first_strand_longer [/tmp/hamming.BsRYhY7oVw/hamming_test.rb:61]:
ArgumentError expected but nothing was raised.
  2) Failure:
HammingTest#test_disallow_second_strand_longer [/tmp/hamming.BsRYhY7oVw/hamming_test.rb:65]:
ArgumentError expected but nothing was raised.
```

Is the solution updated to raise an argument error?

**Comment by r11runner** [comment]
Sorry, I didn't think of it.
Now, I've committed a further change which changed the example implementation accordingly.

**Comment by kytrinyx** [comment]
Awesome!

@markijbema @henrik I know we've been back and forth on whether or not we should have an error case. I'm back to wanting to explicitly handle the error.

In particular, the reason that I wanted to not handle the error, is that this is the first exercise. But now we're about to add "hello world" as the first exercise, so that's not going to be a problem any more.

Thoughts?

**Comment by henrik** [comment]
Was this ever the first exercise? Thought that was Bob?

Is it a goal of Exercism to have a progression from easier to more challenging exercises? Or to at least have that for the first few exercises?

I like about the error case that it introduces another special case to be handled, perhaps making your beautiful solution less so. Just like the real world ;) But I can see that we should skip it if that helps with this progression.

**Comment by kytrinyx** [comment]
This has been the first exercise for a while. It's simpler than Bob, because there's no state in Hamming.

**Comment by kytrinyx** [comment]
Thanks @r11runner -- the Hello World exercise went live yesterday, so this is ready to go.

**Comment by r11runner** [comment]
Thx, great :)

**Comment by markijbema** [comment]
In my opinion, hamming has no meaning for strands of different lengths. So it depends on whether you see this as a standalone program which checks user input, or an internal method (which should be confident) which can just crash by assuming equal lengths. Personally I'm in favour of not checking, but I don't care too much either way.

**Comment by kytrinyx** [comment]
I've gone back and forth, and have ended up leaning more towards the error checking (treating it like a stand-alone library). I think that a good argument can be made either way, and I like the slightly added complexity of having to think about the errors.

**Comment by markijbema** [comment]
I think the most important risk is that people write 'insecure' code (as in opposite of what @avdi talks about in confident code). Since the examples never get large the difference between checking internally and externally isn't really visible. Maybe an exercise where this difference is clear is useful, but I wouldn't really know how to do that without making it large.

**Comment by kytrinyx** [comment]
> I wouldn't really know how to do that without making it large.

Same here.

**Pull request merged**
