### PR TITLE
Remove configlet binary.

### PR DESCRIPTION
**Pull request by dkinzer**
Removes configlet binary that came along for the ride erroneously with
pull request #102.

Adds .gitignore entry for the configlet binary.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Damn -- those binaries are huge. I'm going to do the totally-not-recommended thing and rewrite the history on this one, rather than merge the pull request. This could result in some people getting weird errors if they updated or forked in the past two days, but I'm ok with handling that on a case-by-case basis and walking people through the process of getting it straightened out.

**Comment by kytrinyx** [comment]
> Adds .gitignore entry for the configlet binary.

This bit, though, I will pull in!

**Comment by kytrinyx** [comment]
Included in debd447aa12d9444bbd0c2a69f983477e1c47988

**Comment by dkinzer** [comment]
Yikes.. sorry, :(

**Comment by kytrinyx** [comment]
No, I made it worse than it had to be by slipping in some old binaries earlier. My bad!

**Pull request closed without merging**
