### PR TITLE
Triangle: Update tests to match canonical-data.json.

### PR DESCRIPTION
**Pull request by durrellchamorro**
As discussed at exercism/x-common#311 and exercism/x-common#375 here are my proposed updates to the tests which reflect the canonical-data.json.

### CODE REVIEW

**Comment by kotp** [comment]
@durrellchamorro are you interested in doing the generator for the test so that it can be done once, and regenerated if that json file changes?

**Comment by durrellchamorro** [comment]
I just looked at generator.rb and some of those cases.rb files. It's really neat how you generate the tests this way. I didn't realize that's how it is done and I'm not exactly sure how it all works, so I'll pass on writing the generator for this test. If you don't want to merge this PR, I understand.

**Comment by kotp** [comment]
It is definitely not that I don't want to merge this in, I just know that it will come back because it is not using that data directly, so this will (eventually) need to be revisited.  With that said, the work is done in the form already, and so... it should come in.

:eyes:  @exercism/ruby

**Comment by kotp** [comment]
If by no one objects, I will consider no objections to merging.

**Comment by Insti** [comment]
Correct manually created tests are better than incorrect tests. Merge :+1:

**Pull request merged**
