### PR TITLE
Alphametics: add two cases to test invalid puzzles

### PR DESCRIPTION
**Pull request by repinel**
1. case to check puzzles without a solution.
2. case to check puzzles with leading zero values.

references exercism/x-common#273 and exercism/x-common#277

### CODE REVIEW

**Comment by kotp** [comment]
This looks good to me... anyone else think this is going in the right direction?

**Comment by bernardoamc** [comment]
Looks good to me!

**Comment by kotp** [comment]
Waiting on changes from  exercism/x-common#277

**Comment by kotp** [comment]
This will require a regen after exercism/x-common#277 and exercism/x-common#278 are merged.  @repinel you almost ready?

**Comment by repinel** [comment]
@kotp It should be good now 😉

**Comment by Cohen-Carlisle** [comment]
:+1:

**Comment by repinel** [comment]
Awesome! ❤️

**Pull request merged**
