### PR TITLE
bob: setting up generated tests

### PR DESCRIPTION
**Pull request by raadler**

### CODE REVIEW

**Comment by kotp** [comment]
Are you interested in setting up the generator for these and having the versions mark the occasion?  This is when the bookkeeping becomes important, since it is incremented with the generators to help us keep track of solutions.  

At the moment, there is no reason to change from "Version 0", no change driving it other than to add the bookkeeping itself.

What do you think @raadler, are you up for the task of putting the generator in place?

**Comment by raadler** [comment]
@kotp Sure. Is there documentation I can look at for how to set it up?

**Comment by kotp** [comment]
You can use this same PR... it will automatically update.  May want to change the title to something that indicates setting up generated tests.

**Comment by raadler** [comment]
@kotp A few questions about the generator setup steps: it mentions x-common/$problem.json. Is that x-common/exercises/bob/canonical-data.json in this case? (The path is a bit different than described.) And am I creating the lib/bob.rb? (Some files mentioned in the readme seem to have been renamed, so the readme might need to be edited at some point.)

**Comment by Insti** [comment]
> x-common/$problem.json. Is that x-common/exercises/bob/canonical-data.json in this case?

Yes

>  And am I creating the lib/bob.rb?

You will need to create: 
`lib/bob_cases.rb`
`exercises/bob/example.tt`
`exercises/bob/.version`

If you run the generator with:  `bin/generate bob` it will generate `exercises/bob/bob_test.rb`

The documentation is a bit out of date unfortunately. We're in the middle of changing the process to make everything easier, part of that will involve updating the documentation.

**Comment by Insti** [comment]
Have a look at the recent [Triangle generator](https://github.com/exercism/xruby/pull/474) for an up-to-date example.

**Comment by kotp** [comment]
@raadler I wanted to bump this.  If you want we can pick this up...

**Comment by raadler** [comment]
@kotp That would be great. I've been super busy and this has fallen through the cracks, so if someone has more time for it, go ahead.

**Comment by kotp** [comment]
OK @raadler I am going to close this issue to allow someone else to run with it.  If you find that it has not happened yet, feel free to start from scratch or open this one up and force a push to it to get it rolling again!

**Pull request closed without merging**
